float arclenD(string surface_node, float prim_num, float ustart, float ustop, float divs)
float ceil(float number)
float ch(string channel)
float chrampt(string ramp_path, float position, float component_index, float time)
string copmetas(string compositing_node, string metadata_name)
float degree(string surface_node, float prim_num, float du_or_dv)
float explodematrixpr(matrix mat, vector p, vector pr, string trs, string xyz, string component)
float imgbounds(string foo, string bar, string baz, float qux)
float iprquery(string query, string pane, float x, float y)
string iprquerys(string query, string pane, float x, float y)
string opstreamname(string nodepath)
float property(string foo, float bar)
float propertyf(string foo, float bar, float baz)
string propertys(string foo, string bar)
string propertysop(string foo, string bar)
string propertysraw(string foo, string bar)
float propertyt(string foo, float bar, float baz)
float rint(float number)
float round(float number)
float spknot(string surface_node, float prim_num, float knot_index, float du_or_dv)
float strlen(string s)